"""Packs the character sheets added in October (Aby, enemies, guards, villagers) into
js/chars_assets.js as data URIs, so they also load when the game is opened from file://.
Run:  python tools/pack/pack_chars.py     (or: npm run build:chars)"""
import base64, os, glob
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
out = {}
def add(key, rel):
    with open(os.path.join(ROOT, rel), 'rb') as f:
        out[key] = 'data:image/png;base64,' + base64.b64encode(f.read()).decode()
for f in sorted(glob.glob(os.path.join(ROOT, 'assets/characters/swordsman/*.png'))):
    add('swordsman_' + os.path.basename(f)[:-4], os.path.relpath(f, ROOT))
for d in sorted(glob.glob(os.path.join(ROOT, 'assets/enemies/*/'))):
    eid = os.path.basename(d.rstrip('/\\'))
    for f in sorted(glob.glob(d + '*.png')):
        a = os.path.basename(f)[:-4]
        add('%s_%s' % (eid, 'attack1' if a == 'attack' else a), os.path.relpath(f, ROOT))
add('bone_arrow', 'assets/enemies/bone_arrow.png')
add('necro_bolt', 'assets/enemies/necro_bolt.png')
for d in sorted(glob.glob(os.path.join(ROOT, 'assets/characters/guards/*/'))):
    gid = os.path.basename(d.rstrip('/\\'))
    for f in sorted(glob.glob(d + '*.png')):
        add('g_%s_%s' % (gid, os.path.basename(f)[:-4]), os.path.relpath(f, ROOT))
for i, n in enumerate(['MiniNobleWoman', 'MiniOldMan', 'MiniOldWoman', 'MiniPrincess', 'MiniQueen', 'MiniWorker']):
    add('npc%d_villager' % (i + 5), 'assets/npc/%s.png' % n)
with open(os.path.join(ROOT, 'js/chars_assets.js'), 'w') as f:
    f.write('/* GENERATED by tools/pack/pack_chars.py - character sheets embedded as data URIs (file:// friendly). */\n')
    f.write('window.GAME_ASSETS_BASE64 = window.GAME_ASSETS_BASE64 || {};\n')
    for k, v in out.items():
        f.write("window.GAME_ASSETS_BASE64.%s = '%s';\n" % (k, v))
print(len(out), 'sheets')
